apiVersion: v1
kind: Pod
metadata:
  name:
  labels:
    app:
spec:
  containers:
  - name:
    image: allen13/helloworld:v0.1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"